-- Database Schema for Club-MET Platform (Supabase PostgreSQL)

-- 1. Users Profile Table (extends Supabase Auth)
CREATE TABLE public.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nom TEXT NOT NULL,
    prenom TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    niveau TEXT NOT NULL, -- Class levels, e.g. TC1, Licence 1 IT, etc.
    role TEXT DEFAULT 'student', -- 'student' or 'admin'
    avatar_url TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for users
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to users profiles" ON public.users
    FOR SELECT USING (true);

CREATE POLICY "Allow users to update their own profile" ON public.users
    FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Allow users to insert their profile on registration" ON public.users
    FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Allow admins to delete users" ON public.users
    FOR DELETE USING (
        EXISTS (
            SELECT 1 FROM public.users
            WHERE users.id = auth.uid() AND users.role = 'admin'
        )
    );

-- 2. Bureau Executive Members Table
CREATE TABLE public.bureau (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom TEXT NOT NULL,
    poste TEXT NOT NULL,
    classe TEXT NOT NULL,
    imageUrl TEXT,
    whatsapp TEXT,
    linkedin TEXT,
    "estAncien" BOOLEAN DEFAULT false,
    annee TEXT,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.bureau ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to bureau members" ON public.bureau
    FOR SELECT USING (true);

CREATE POLICY "Allow admin write access to bureau" ON public.bureau
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.users
            WHERE users.id = auth.uid() AND users.role = 'admin'
        )
    );

-- 3. Academic Ressources (Documents) Table
CREATE TABLE public.ressources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom TEXT NOT NULL,
    url TEXT NOT NULL,
    categorie TEXT NOT NULL, -- e.g. 'reglement', 'rapports', 'comptes_rendus'
    typeDoc TEXT,           -- e.g. 'PDF', 'Word'
    date TEXT,
    description TEXT,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.ressources ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to ressources" ON public.ressources
    FOR SELECT USING (true);

CREATE POLICY "Allow admin write access to ressources" ON public.ressources
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.users
            WHERE users.id = auth.uid() AND users.role = 'admin'
        )
    );

-- 4. Maquettes (Syllabus) Table
CREATE TABLE public.maquettes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filiere TEXT NOT NULL, -- e.g. 'HEC', 'IT'
    nom TEXT NOT NULL,
    url TEXT NOT NULL,
    createdAt TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.maquettes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to maquettes" ON public.maquettes
    FOR SELECT USING (true);

CREATE POLICY "Allow admin write access to maquettes" ON public.maquettes
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.users
            WHERE users.id = auth.uid() AND users.role = 'admin'
        )
    );

-- 5. Bibliotheque (Pédagogique) Table
CREATE TABLE public.bibliotheque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom TEXT NOT NULL,
    url TEXT NOT NULL,
    categorie TEXT NOT NULL, -- e.g. 'cours', 'td', 'examens'
    niveau TEXT NOT NULL,    -- e.g. 'L1', 'L2', 'L3', 'M1', 'M2', 'Commun'
    description TEXT,
    date_ajout TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.bibliotheque ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to bibliotheque" ON public.bibliotheque
    FOR SELECT USING (true);

CREATE POLICY "Allow admin write access to bibliotheque" ON public.bibliotheque
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.users
            WHERE users.id = auth.uid() AND users.role = 'admin'
        )
    );

-- 6. Activites (Events) Table
CREATE TABLE public.activites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre TEXT NOT NULL,
    type TEXT NOT NULL,
    date TEXT NOT NULL,
    description TEXT,
    image_url TEXT
);

ALTER TABLE public.activites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to activites" ON public.activites
    FOR SELECT USING (true);

CREATE POLICY "Allow admin write access to activites" ON public.activites
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.users
            WHERE users.id = auth.uid() AND users.role = 'admin'
        )
    );

-- 7. Medias (Photo/Video Gallery) Table
CREATE TABLE public.medias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre TEXT,
    description TEXT,
    type TEXT NOT NULL, -- 'Photo' or 'Vidéo'
    url TEXT NOT NULL,
    date_ajout TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.medias ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to medias" ON public.medias
    FOR SELECT USING (true);

CREATE POLICY "Allow admin write access to medias" ON public.medias
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.users
            WHERE users.id = auth.uid() AND users.role = 'admin'
        )
    );

-- 8. Messages Table (Tutorat/Contact)
CREATE TABLE public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom TEXT NOT NULL,
    email TEXT NOT NULL,
    telephone TEXT,
    message TEXT NOT NULL,
    statut TEXT DEFAULT 'non_lu' NOT NULL, -- 'non_lu' or 'lu'
    objet TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow students to view their own messages" ON public.messages
    FOR SELECT USING (email = (SELECT email FROM public.users WHERE id = auth.uid()));

CREATE POLICY "Allow public/students to submit contact messages" ON public.messages
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow admins full access to messages" ON public.messages
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.users
            WHERE users.id = auth.uid() AND users.role = 'admin'
        )
    );

-- 9. Notifications Table (Push broadcasts)
CREATE TABLE public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message TEXT NOT NULL,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to notifications" ON public.notifications
    FOR SELECT USING (true);

CREATE POLICY "Allow admin write access to notifications" ON public.notifications
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.users
            WHERE users.id = auth.uid() AND users.role = 'admin'
        )
    );

-- 10. Config Table (dynamic keys)
CREATE TABLE public.config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cle TEXT UNIQUE NOT NULL,
    valeur TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.config ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to config" ON public.config FOR SELECT USING (true);
CREATE POLICY "Allow admin write access to config" ON public.config FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.users
        WHERE users.id = auth.uid() AND users.role = 'admin'
    )
);

-- 11. Cotisations Table (Dues/Contributions)
CREATE TABLE public.cotisations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    nom TEXT NOT NULL,
    classe TEXT NOT NULL,
    montant NUMERIC NOT NULL,
    date_paiement TEXT NOT NULL,
    statut TEXT DEFAULT 'valide' NOT NULL, -- 'valide', 'en_attente'
    enregistre_par TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.cotisations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow users to view their own cotisations" ON public.cotisations FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "Allow users to insert their cotisations" ON public.cotisations FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY "Allow admin full access to cotisations" ON public.cotisations FOR ALL USING (
    EXISTS (
        SELECT 1 FROM public.users
        WHERE users.id = auth.uid() AND users.role = 'admin'
    )
);
